name: Run All Crawlers - 20min / Vancouver 08:00~24:00

on:
  schedule:
    - cron: '*/20 0-7,16-23 * * *'  # ✅ 20분 주기, Vancouver 기준 08시~24시
  workflow_dispatch:

jobs:
  run-crawlers:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run all crawlers
        run: node utilities/crawler/runAllCrawlers.js
