name: Merge Vancouver Crawldata - 35min / Vancouver 08:00~24:00

on:
  schedule:
    - cron: '0,30 0-7,16-23 * * *'  # 35분 주기 (UTC 기준으로 캐나다 08:00~24:00)
  workflow_dispatch:

jobs:
  merge-vancouver:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run merge logic
        run: node utilities/serverutil/mergeVancouverSupabase.js
